/**
 * Mapping Engine - Core Transformation Orchestration
 */

import { get, set, cloneDeep } from 'lodash';
import {
  MappingConfig,
  MappingResult,
  MappingReport,
  MappingEntry,
  MappingRule,
  TransformationContext,
} from './types';
import { transformFunctions } from './transformations';

/**
 * Main transformation engine
 */
export class MappingEngine {
  private config: MappingConfig;

  constructor(config: MappingConfig) {
    this.config = config;
  }

  /**
   * Transform SAP Order to One Record Canonical Order
   */
  async transform(sapOrder: any): Promise<MappingResult> {
    const errors: string[] = [];
    const mappings: MappingEntry[] = [];
    const canonicalOrder: any = {};

    try {
      // Initialize context
      const context: TransformationContext = {
        source: sapOrder,
        sourceValue: null,
        sourcePath: '',
        targetPath: '',
        config: this.config,
      };

      // Apply all mapping rules
      for (const rule of this.config.rules) {
        try {
          const entry = await this.applyRule(rule, sapOrder, canonicalOrder, context);
          if (entry) {
            mappings.push(entry);
          }
        } catch (error) {
          errors.push(`Rule ${rule.sourcePath} → ${rule.targetPath}: ${error}`);
        }
      }

      // Handle line items (array iteration)
      await this.handleLineItems(sapOrder, canonicalOrder, mappings, context);

      // Generate mapping report
      const report = this.generateReport(sapOrder, canonicalOrder, mappings, errors);

      return {
        canonicalOrder,
        report,
        success: errors.length === 0,
        errors: errors.length > 0 ? errors : undefined,
      };
    } catch (error) {
      return {
        canonicalOrder: {},
        report: this.generateEmptyReport(sapOrder),
        success: false,
        errors: [`Fatal transformation error: ${error}`],
      };
    }
  }

  /**
   * Apply a single mapping rule
   */
  private async applyRule(
    rule: MappingRule,
    source: any,
    target: any,
    baseContext: TransformationContext
  ): Promise<MappingEntry | null> {
    // Skip array rules (handled separately)
    if (rule.sourcePath.includes('[*]')) {
      return null;
    }

    // Get source value
    let sourceValue: any;
    if (rule.sourcePath.startsWith('_static') || rule.sourcePath.startsWith('_metadata')) {
      sourceValue = null; // Will be generated by transform function
    } else {
      sourceValue = get(source, rule.sourcePath);
    }

    // Skip if source is missing and no default
    if (sourceValue === undefined && !rule.defaultValue && !rule.transformFunction) {
      return null;
    }

    // Apply transformation or use value directly
    const context: TransformationContext = {
      ...baseContext,
      sourceValue: sourceValue ?? rule.defaultValue,
      sourcePath: rule.sourcePath,
      targetPath: rule.targetPath,
    };

    let targetValue: any;
    let transformationApplied: string | undefined;

    if (rule.transformFunction) {
      const fn = transformFunctions[rule.transformFunction];
      if (!fn) {
        throw new Error(`Transform function not found: ${rule.transformFunction}`);
      }
      targetValue = fn(context);
      transformationApplied = rule.transformFunction;
    } else {
      targetValue = sourceValue ?? rule.defaultValue;
    }

    // Set target value
    if (targetValue !== undefined && targetValue !== null) {
      set(target, rule.targetPath, targetValue);
    }

    // Create mapping entry
    return {
      sourcePath: rule.sourcePath,
      targetPath: rule.targetPath,
      targetSemanticReference: rule.targetSemanticReference,
      mappingType: rule.mappingType,
      confidence: rule.confidence,
      rationale: rule.rationale || 'Direct mapping',
      sourceValue: sourceValue ?? rule.defaultValue,
      targetValue,
      transformationApplied,
    };
  }

  /**
   * Handle line items array mapping
   */
  private async handleLineItems(
    source: any,
    target: any,
    mappings: MappingEntry[],
    baseContext: TransformationContext
  ): Promise<void> {
    const orderItems = get(source, 'OrderItems');
    if (!Array.isArray(orderItems) || orderItems.length === 0) {
      return;
    }

    // Get line item rules
    const lineItemRules = this.config.rules.filter(r => r.sourcePath.includes('[*]'));

    // Initialize target array
    target.orderLine = [];

    // Process each item
    for (let i = 0; i < orderItems.length; i++) {
      const lineItem: any = {};

      for (const rule of lineItemRules) {
        const sourcePath = rule.sourcePath.replace('[*]', `[${i}]`);
        const targetPath = rule.targetPath.replace('[*]', `[${i}]`);

        let sourceValue = get(source, sourcePath);

        // Handle header-level references (e.g., DocumentCurrency)
        if (!sourceValue && sourcePath.includes('OrderHeader')) {
          sourceValue = get(source, sourcePath);
        }

        const context: TransformationContext = {
          ...baseContext,
          sourceValue,
          sourcePath,
          targetPath,
        };

        let targetValue: any;
        let transformationApplied: string | undefined;

        if (rule.transformFunction) {
          const fn = transformFunctions[rule.transformFunction];
          if (fn) {
            targetValue = fn(context);
            transformationApplied = rule.transformFunction;
          }
        } else {
          targetValue = sourceValue;
        }

        if (targetValue !== undefined && targetValue !== null) {
          // Remove [*] notation for setting in object
          const cleanTargetPath = rule.targetPath.replace('[*].', '');
          set(lineItem, cleanTargetPath, targetValue);
        }

        mappings.push({
          sourcePath,
          targetPath: `orderLine[${i}].` + rule.targetPath.replace('[*].', ''),
          targetSemanticReference: rule.targetSemanticReference,
          mappingType: rule.mappingType,
          confidence: rule.confidence,
          rationale: rule.rationale || 'Line item mapping',
          sourceValue,
          targetValue,
          transformationApplied,
        });
      }

      target.orderLine.push(lineItem);
    }
  }

  /**
   * Generate comprehensive mapping report
   */
  private generateReport(
    source: any,
    target: any,
    mappings: MappingEntry[],
    errors: string[]
  ): MappingReport {
    const timestamp = new Date().toISOString();
    const sourceDocumentID = get(source, 'OrderHeader.SalesDocument', 'unknown');

    // Identify unmapped source fields
    const unmappedSourceFields = this.findUnmappedSourceFields(source, mappings);

    // Identify missing required target fields
    const missingRequiredFields = this.findMissingRequiredFields(target, this.config.rules);

    // Calculate confidence statistics
    const statistics = {
      totalSourceFields: this.countFields(source),
      totalMappedFields: mappings.length,
      totalUnmappedFields: unmappedSourceFields.length,
      highConfidenceMappings: mappings.filter(m => m.confidence === 'HIGH').length,
      mediumConfidenceMappings: mappings.filter(m => m.confidence === 'MEDIUM').length,
      lowConfidenceMappings: mappings.filter(m => m.confidence === 'LOW').length,
    };

    // Calculate overall confidence (weighted average)
    const confidenceWeights = { HIGH: 100, MEDIUM: 75, LOW: 50, SUGGEST: 25 };
    const totalConfidence = mappings.reduce((sum, m) => {
      return sum + (confidenceWeights[m.confidence] || 0);
    }, 0);
    const overallConfidence = mappings.length > 0 
      ? Math.round(totalConfidence / mappings.length)
      : 0;

    // Document semantic assumptions
    const semanticAssumptions = [
      {
        assumption: 'SAP tax codes map to UBL tax categories (S1→S, S0→Z, etc.)',
        affectedFields: mappings
          .filter(m => m.transformationApplied === 'sapTaxCodeToUBL')
          .map(m => m.targetPath),
        rationale: 'Based on common EU VAT practice; may vary by jurisdiction',
      },
      {
        assumption: 'SAP unit of measure codes map to UN/CEFACT Rec. 20 codes',
        affectedFields: mappings
          .filter(m => m.transformationApplied === 'sapUoMToUNCEFACT')
          .map(m => m.targetPath),
        rationale: 'Standard international UoM code mapping',
      },
      {
        assumption: 'Tax scheme is VAT for EU/Finnish context',
        affectedFields: mappings
          .filter(m => m.transformationApplied === 'staticTaxScheme')
          .map(m => m.targetPath),
        rationale: 'Finnish business scenario assumes VAT taxation',
      },
      {
        assumption: 'Seller party details require master data configuration',
        affectedFields: ['sellerSupplierParty.partyName[0].name', 'sellerSupplierParty.postalAddress'],
        rationale: 'Sales organization code requires lookup to get company details',
      },
    ].filter(a => a.affectedFields.length > 0);

    return {
      timestamp,
      sourceDocumentID,
      mappingEngineVersion: this.config.metadata.version,
      mappingRulesVersion: this.config.metadata.rulesVersion,
      mappings,
      unmappedSourceFields,
      missingRequiredFields,
      semanticAssumptions,
      overallConfidence,
      statistics,
    };
  }

  /**
   * Find unmapped source fields
   */
  private findUnmappedSourceFields(source: any, mappings: MappingEntry[]): Array<{
    path: string;
    value: any;
    reason: string;
  }> {
    const mappedPaths = new Set(mappings.map(m => m.sourcePath));
    const unmapped: Array<{ path: string; value: any; reason: string }> = [];

    // Check known SAP fields that are typically unmapped
    const knownUnmappedFields = [
      { path: 'OrderHeader.SalesOffice', reason: 'SAP-internal organizational field' },
      { path: 'OrderHeader.SalesGroup', reason: 'SAP-internal organizational field' },
      { path: 'OrderHeader.Division', reason: 'SAP-internal product organization' },
      { path: 'OrderHeader.DistributionChannel', reason: 'SAP-internal sales channel' },
      { path: 'Status', reason: 'Runtime processing status, not part of Order document' },
    ];

    for (const field of knownUnmappedFields) {
      const value = get(source, field.path);
      if (value !== undefined && !mappedPaths.has(field.path)) {
        unmapped.push({ path: field.path, value, reason: field.reason });
      }
    }

    return unmapped;
  }

  /**
   * Find missing required target fields
   */
  private findMissingRequiredFields(target: any, rules: MappingRule[]): Array<{
    path: string;
    semanticReference?: string;
    reason: string;
  }> {
    const missing: Array<{ path: string; semanticReference?: string; reason: string }> = [];

    for (const rule of rules) {
      if (rule.required) {
        const value = get(target, rule.targetPath);
        if (value === undefined || value === null) {
          missing.push({
            path: rule.targetPath,
            semanticReference: rule.targetSemanticReference,
            reason: `Required field ${rule.targetPath} not populated from ${rule.sourcePath}`,
          });
        }
      }
    }

    return missing;
  }

  /**
   * Count total fields in source object
   */
  private countFields(obj: any, prefix = ''): number {
    let count = 0;

    for (const key in obj) {
      if (obj.hasOwnProperty(key)) {
        const value = obj[key];
        const path = prefix ? `${prefix}.${key}` : key;

        if (value && typeof value === 'object' && !Array.isArray(value)) {
          count += this.countFields(value, path);
        } else if (Array.isArray(value)) {
          count++; // Count array as one field
        } else {
          count++;
        }
      }
    }

    return count;
  }

  /**
   * Generate empty report on error
   */
  private generateEmptyReport(source: any): MappingReport {
    return {
      timestamp: new Date().toISOString(),
      sourceDocumentID: get(source, 'OrderHeader.SalesDocument', 'unknown'),
      mappingEngineVersion: this.config.metadata.version,
      mappingRulesVersion: this.config.metadata.rulesVersion,
      mappings: [],
      unmappedSourceFields: [],
      missingRequiredFields: [],
      semanticAssumptions: [],
      overallConfidence: 0,
      statistics: {
        totalSourceFields: 0,
        totalMappedFields: 0,
        totalUnmappedFields: 0,
        highConfidenceMappings: 0,
        mediumConfidenceMappings: 0,
        lowConfidenceMappings: 0,
      },
    };
  }
}
